services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080" # 主機的 8000 埠映射到容器內的 8080 埠
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
    depends_on:
      database:
        condition: service_healthy  # Make sure MySQL is healthy before starting
      restart: unless-stopped  # 確保異常停止時自動重啟
      networks:
        - backend

  database:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306" # 主機的 3307 埠映射到容器內的 3306 埠
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
      networks:
        - backend

volumes:
  db_data:

networks:
  backend: